# Twitter Financial News Sentiment Dataset & Reddit Crypto Sentiment Dataset

## Observations

- Size of a Combined dataset is __3914 (samples)__
- For more granular levl details please scroll down and look the output.

## Combining two dataset together

In [1]:
import pandas as pd
import numpy as np

In [2]:
import re
import string
import json
from spacy.lang.en.stop_words import STOP_WORDS

C:\Users\darsh\anaconda3\envs\reddit_sentiment_cls\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Reddit Crypto Comments Sentiment

In [3]:
reddit_data_df = pd.read_csv("../data/processed_dataset_opt.csv")
reddit_data_df

,class,sentiment,comment_text,processed_text
0,1,Positive,"I bought 2200 at the ico, at 0.50$ per coin. H...",bought 2200 ico 050 coin hold sold 3 months ag...
1,1,Positive,"Harmony one , algorand , Cardano, solana , vec...",harmony algorand cardano solana vechain gonna ...
2,0,Negative,"Honestly, after reading this post and many of ...",honestly reading post responses conclude crypt...
3,1,Positive,In bear market is where money is made. I Will ...,bear market money continue dca assets believe
4,0,Negative,Funny how people think Bitcoin's risk is compa...,funny people think bitcoins risk comparable st...
...,...,...,...,...
547,1,Positive,Lightning Network has the capability to do mil...,lightning network capability millions btc tran...
548,1,Positive,It means there will be more daily volume which...,means daily volume means daily active users me...
549,0,Negative,The exchanges were so irresponsible to list th...,exchanges irresponsible list tokens luna shoul...
550,1,Positive,Massive ecosystem. Pretty much all application...,massive ecosystem pretty applications shitload...
551,1,Positive,I’m actually excited because I had cash on the...,i’m actually excited cash moments like

In [4]:
reddit_data_df["source"] = "reddit"
reddit_data_df

,class,sentiment,comment_text,processed_text,source
0,1,Positive,"I bought 2200 at the ico, at 0.50$ per coin. H...",bought 2200 ico 050 coin hold sold 3 months ag...,reddit
1,1,Positive,"Harmony one , algorand , Cardano, solana , vec...",harmony algorand cardano solana vechain gonna ...,reddit
2,0,Negative,"Honestly, after reading this post and many of ...",honestly reading post responses conclude crypt...,reddit
3,1,Positive,In bear market is where money is made. I Will ...,bear market money continue dca assets believe,reddit
4,0,Negative,Funny how people think Bitcoin's risk is compa...,funny people think bitcoins risk comparable st...,reddit
...,...,...,...,...,...
547,1,Positive,Lightning Network has the capability to do mil...,lightning network capability millions btc tran...,reddit
548,1,Positive,It means there will be more daily volume which...,means daily volume means daily active users me...,reddit
549,0,Negative,The exchanges were so irresponsible to list th...,exchanges irresponsible list tokens luna shoul...,reddit
550,1,Positive,Massive ecosystem. Pretty much all application...,massive ecosystem pretty applications shitload...,reddit
551,1,Positive,I’m actually excited because I had cash on the...,i’m actually excited cash moments like,reddit

In [5]:
reddit_dup_data_df = reddit_data_df[reddit_data_df.duplicated(subset = ['processed_text','sentiment'])]
reddit_dup_data_df

,class,sentiment,comment_text,processed_text,source
362,1,Positive,Bitcoin is going to win. Traditional finance i...,bitcoin going win traditional finance obsolete...,reddit
456,1,Positive,Yup. Still mega bullish on DOTs canary chain K...,yup mega bullish dots canary chain kusama,reddit

In [6]:
reddit_data_df = reddit_data_df.drop(labels=list(reddit_dup_data_df.index), axis=0)
reddit_data_df

,class,sentiment,comment_text,processed_text,source
0,1,Positive,"I bought 2200 at the ico, at 0.50$ per coin. H...",bought 2200 ico 050 coin hold sold 3 months ag...,reddit
1,1,Positive,"Harmony one , algorand , Cardano, solana , vec...",harmony algorand cardano solana vechain gonna ...,reddit
2,0,Negative,"Honestly, after reading this post and many of ...",honestly reading post responses conclude crypt...,reddit
3,1,Positive,In bear market is where money is made. I Will ...,bear market money continue dca assets believe,reddit
4,0,Negative,Funny how people think Bitcoin's risk is compa...,funny people think bitcoins risk comparable st...,reddit
...,...,...,...,...,...
547,1,Positive,Lightning Network has the capability to do mil...,lightning network capability millions btc tran...,reddit
548,1,Positive,It means there will be more daily volume which...,means daily volume means daily active users me...,reddit
549,0,Negative,The exchanges were so irresponsible to list th...,exchanges irresponsible list tokens luna shoul...,reddit
550,1,Positive,Massive ecosystem. Pretty much all application...,massive ecosystem pretty applications shitload...,reddit
551,1,Positive,I’m actually excited because I had cash on the...,i’m actually excited cash moments like,reddit

In [7]:
reddit_data_df.describe()

            class
count  550.000000
mean     0.534545
std      0.499259
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000

In [8]:
reddit_data_df['sentiment'].value_counts()

Positive    294
Negative    256
Name: sentiment, dtype: int64

### Twitter Financial News Sentiment

In [9]:
twns_data_df = pd.read_csv("../data/twitter-financial-news-sentiment/processed_dataset.csv")
twns_data_df

,class,sentiment,text,processed_text
0,0,Negative,$BYND - JPMorgan reels in expectations on Beyo...,bynd jpmorgan reels expectations meat httpstco...
1,0,Negative,$CCL $RCL - Nomura points to bookings weakness...,ccl rcl nomura points bookings weakness carniv...
2,0,Negative,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",cx cemex cut credit suisse jp morgan weak buil...
3,0,Negative,$ESS: BTIG Research cuts to Neutral https://t....,ess btig research cuts neutral httpstcomcyftsxc2n
4,0,Negative,$FNKO - Funko slides after Piper Jaffray PT cu...,fnko funko slides piper jaffray pt cut httpstc...
...,...,...,...,...
3360,1,Positive,Why Slack Stock Just Surged 17%,slack stock surged 17
3361,1,Positive,Why Tiffany Stock Just Popped 6%,tiffany stock popped 6
3362,1,Positive,WiLAN signs wireless license with LG; shares +...,wilan signs wireless license lg shares 7 pm
3363,1,Positive,"Yandex authorizes share repurchase program, sh...",yandex authorizes share repurchase program sha...
3364,1,Positive,Zscaler +2.6% on new bull ahead of earnings,zscaler 26 new bull ahead earnings

In [10]:
twns_data_df["source"] = "twitter"
twns_data_df

,class,sentiment,text,processed_text,source
0,0,Negative,$BYND - JPMorgan reels in expectations on Beyo...,bynd jpmorgan reels expectations meat httpstco...,twitter
1,0,Negative,$CCL $RCL - Nomura points to bookings weakness...,ccl rcl nomura points bookings weakness carniv...,twitter
2,0,Negative,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",cx cemex cut credit suisse jp morgan weak buil...,twitter
3,0,Negative,$ESS: BTIG Research cuts to Neutral https://t....,ess btig research cuts neutral httpstcomcyftsxc2n,twitter
4,0,Negative,$FNKO - Funko slides after Piper Jaffray PT cu...,fnko funko slides piper jaffray pt cut httpstc...,twitter
...,...,...,...,...,...
3360,1,Positive,Why Slack Stock Just Surged 17%,slack stock surged 17,twitter
3361,1,Positive,Why Tiffany Stock Just Popped 6%,tiffany stock popped 6,twitter
3362,1,Positive,WiLAN signs wireless license with LG; shares +...,wilan signs wireless license lg shares 7 pm,twitter
3363,1,Positive,"Yandex authorizes share repurchase program, sh...",yandex authorizes share repurchase program sha...,twitter
3364,1,Positive,Zscaler +2.6% on new bull ahead of earnings,zscaler 26 new bull ahead earnings,twitter

In [11]:
twns_data_df.rename(columns={"text": "comment_text"}, inplace=True)
twns_data_df

,class,sentiment,comment_text,processed_text,source
0,0,Negative,$BYND - JPMorgan reels in expectations on Beyo...,bynd jpmorgan reels expectations meat httpstco...,twitter
1,0,Negative,$CCL $RCL - Nomura points to bookings weakness...,ccl rcl nomura points bookings weakness carniv...,twitter
2,0,Negative,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",cx cemex cut credit suisse jp morgan weak buil...,twitter
3,0,Negative,$ESS: BTIG Research cuts to Neutral https://t....,ess btig research cuts neutral httpstcomcyftsxc2n,twitter
4,0,Negative,$FNKO - Funko slides after Piper Jaffray PT cu...,fnko funko slides piper jaffray pt cut httpstc...,twitter
...,...,...,...,...,...
3360,1,Positive,Why Slack Stock Just Surged 17%,slack stock surged 17,twitter
3361,1,Positive,Why Tiffany Stock Just Popped 6%,tiffany stock popped 6,twitter
3362,1,Positive,WiLAN signs wireless license with LG; shares +...,wilan signs wireless license lg shares 7 pm,twitter
3363,1,Positive,"Yandex authorizes share repurchase program, sh...",yandex authorizes share repurchase program sha...,twitter
3364,1,Positive,Zscaler +2.6% on new bull ahead of earnings,zscaler 26 new bull ahead earnings,twitter

In [12]:
twns_dup_data_df = twns_data_df[twns_data_df.duplicated(subset = ['processed_text','sentiment'])]
twns_dup_data_df

,class,sentiment,comment_text,processed_text,source
1260,1,Positive,Total Profit Beats Estimates on Rising Oil and...,total profit beats estimates rising oil gas ou...,twitter

In [13]:
twns_data_df = twns_data_df.drop(labels=list(twns_dup_data_df.index), axis=0)
twns_data_df

,class,sentiment,comment_text,processed_text,source
0,0,Negative,$BYND - JPMorgan reels in expectations on Beyo...,bynd jpmorgan reels expectations meat httpstco...,twitter
1,0,Negative,$CCL $RCL - Nomura points to bookings weakness...,ccl rcl nomura points bookings weakness carniv...,twitter
2,0,Negative,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",cx cemex cut credit suisse jp morgan weak buil...,twitter
3,0,Negative,$ESS: BTIG Research cuts to Neutral https://t....,ess btig research cuts neutral httpstcomcyftsxc2n,twitter
4,0,Negative,$FNKO - Funko slides after Piper Jaffray PT cu...,fnko funko slides piper jaffray pt cut httpstc...,twitter
...,...,...,...,...,...
3360,1,Positive,Why Slack Stock Just Surged 17%,slack stock surged 17,twitter
3361,1,Positive,Why Tiffany Stock Just Popped 6%,tiffany stock popped 6,twitter
3362,1,Positive,WiLAN signs wireless license with LG; shares +...,wilan signs wireless license lg shares 7 pm,twitter
3363,1,Positive,"Yandex authorizes share repurchase program, sh...",yandex authorizes share repurchase program sha...,twitter
3364,1,Positive,Zscaler +2.6% on new bull ahead of earnings,zscaler 26 new bull ahead earnings,twitter

In [14]:
twns_data_df.describe()

             class
count  3364.000000
mean      0.571344
std       0.494957
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [15]:
twns_data_df['sentiment'].value_counts()

Positive    1922
Negative    1442
Name: sentiment, dtype: int64

## Combined Dataset

In [16]:
combined_data_df = pd.concat([reddit_data_df, twns_data_df], axis=0)
combined_data_df

,class,sentiment,comment_text,processed_text,source
0,1,Positive,"I bought 2200 at the ico, at 0.50$ per coin. H...",bought 2200 ico 050 coin hold sold 3 months ag...,reddit
1,1,Positive,"Harmony one , algorand , Cardano, solana , vec...",harmony algorand cardano solana vechain gonna ...,reddit
2,0,Negative,"Honestly, after reading this post and many of ...",honestly reading post responses conclude crypt...,reddit
3,1,Positive,In bear market is where money is made. I Will ...,bear market money continue dca assets believe,reddit
4,0,Negative,Funny how people think Bitcoin's risk is compa...,funny people think bitcoins risk comparable st...,reddit
...,...,...,...,...,...
3360,1,Positive,Why Slack Stock Just Surged 17%,slack stock surged 17,twitter
3361,1,Positive,Why Tiffany Stock Just Popped 6%,tiffany stock popped 6,twitter
3362,1,Positive,WiLAN signs wireless license with LG; shares +...,wilan signs wireless license lg shares 7 pm,twitter
3363,1,Positive,"Yandex authorizes share repurchase program, sh...",yandex authorizes share repurchase program sha...,twitter
3364,1,Positive,Zscaler +2.6% on new bull ahead of earnings,zscaler 26 new bull ahead earnings,twitter

In [17]:
combined_data_df.groupby(["source", "sentiment"]).count()

                   class  comment_text  processed_text
source  sentiment
reddit  Negative     256           256             256
        Positive     294           294             294
twitter Negative    1442          1442            1442
        Positive    1922          1922            1922

### Saving Combined dataset on disk

In [18]:
combined_data_df.to_csv("../data/processed_combined_dataset.csv", index=False)